// Code generated by Stan version 2.18.0

#include <stan/model/model_header.hpp>

namespace m12_6_1_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "/home/travis/build/StanJulia/StatisticalRethinking.jl/docs/build/12/tmp/m12.6.1.stan");
    reader.add_event(25, 23, "end", "/home/travis/build/StanJulia/StatisticalRethinking.jl/docs/build/12/tmp/m12.6.1.stan");
    return reader;
}

class m12_6_1_model : public prob_grad {
private:
    vector<int> total_tools;
    vector<double> logpop;
    vector<int> society;
public:
    m12_6_1_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    m12_6_1_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "m12_6_1_model_namespace::m12_6_1_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 2;
            validate_non_negative_index("total_tools", "10", 10);
            context__.validate_dims("data initialization", "total_tools", "int", context__.to_vec(10));
            validate_non_negative_index("total_tools", "10", 10);
            total_tools = std::vector<int>(10,int(0));
            vals_i__ = context__.vals_i("total_tools");
            pos__ = 0;
            size_t total_tools_limit_0__ = 10;
            for (size_t i_0__ = 0; i_0__ < total_tools_limit_0__; ++i_0__) {
                total_tools[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 3;
            validate_non_negative_index("logpop", "10", 10);
            context__.validate_dims("data initialization", "logpop", "double", context__.to_vec(10));
            validate_non_negative_index("logpop", "10", 10);
            logpop = std::vector<double>(10,double(0));
            vals_r__ = context__.vals_r("logpop");
            pos__ = 0;
            size_t logpop_limit_0__ = 10;
            for (size_t i_0__ = 0; i_0__ < logpop_limit_0__; ++i_0__) {
                logpop[i_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 4;
            validate_non_negative_index("society", "10", 10);
            context__.validate_dims("data initialization", "society", "int", context__.to_vec(10));
            validate_non_negative_index("society", "10", 10);
            society = std::vector<int>(10,int(0));
            vals_i__ = context__.vals_i("society");
            pos__ = 0;
            size_t society_limit_0__ = 10;
            for (size_t i_0__ = 0; i_0__ < society_limit_0__; ++i_0__) {
                society[i_0__] = vals_i__[pos__++];
            }

            // validate, data variables
            current_statement_begin__ = 2;
            current_statement_begin__ = 3;
            current_statement_begin__ = 4;
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 7;
            ++num_params_r__;
            current_statement_begin__ = 8;
            ++num_params_r__;
            current_statement_begin__ = 9;
            validate_non_negative_index("a_society", "10", 10);
            num_params_r__ += 10;
            current_statement_begin__ = 10;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~m12_6_1_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("a")))
            throw std::runtime_error("variable a missing");
        vals_r__ = context__.vals_r("a");
        pos__ = 0U;
        context__.validate_dims("initialization", "a", "double", context__.to_vec());
        double a(0);
        a = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(a);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a: ") + e.what());
        }

        if (!(context__.contains_r("bp")))
            throw std::runtime_error("variable bp missing");
        vals_r__ = context__.vals_r("bp");
        pos__ = 0U;
        context__.validate_dims("initialization", "bp", "double", context__.to_vec());
        double bp(0);
        bp = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(bp);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable bp: ") + e.what());
        }

        if (!(context__.contains_r("a_society")))
            throw std::runtime_error("variable a_society missing");
        vals_r__ = context__.vals_r("a_society");
        pos__ = 0U;
        validate_non_negative_index("a_society", "10", 10);
        context__.validate_dims("initialization", "a_society", "vector_d", context__.to_vec(10));
        vector_d a_society(static_cast<Eigen::VectorXd::Index>(10));
        for (int j1__ = 0U; j1__ < 10; ++j1__)
            a_society(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(a_society);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a_society: ") + e.what());
        }

        if (!(context__.contains_r("sigma_society")))
            throw std::runtime_error("variable sigma_society missing");
        vals_r__ = context__.vals_r("sigma_society");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigma_society", "double", context__.to_vec());
        double sigma_society(0);
        sigma_society = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigma_society);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigma_society: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            local_scalar_t__ a;
            (void) a;  // dummy to suppress unused var warning
            if (jacobian__)
                a = in__.scalar_constrain(lp__);
            else
                a = in__.scalar_constrain();

            local_scalar_t__ bp;
            (void) bp;  // dummy to suppress unused var warning
            if (jacobian__)
                bp = in__.scalar_constrain(lp__);
            else
                bp = in__.scalar_constrain();

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  a_society;
            (void) a_society;  // dummy to suppress unused var warning
            if (jacobian__)
                a_society = in__.vector_constrain(10,lp__);
            else
                a_society = in__.vector_constrain(10);

            local_scalar_t__ sigma_society;
            (void) sigma_society;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma_society = in__.scalar_lb_constrain(0,lp__);
            else
                sigma_society = in__.scalar_lb_constrain(0);


            // transformed parameters



            // validate transformed parameters

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // model body
            {
            current_statement_begin__ = 13;
            validate_non_negative_index("mu", "10", 10);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  mu(static_cast<Eigen::VectorXd::Index>(10));
            (void) mu;  // dummy to suppress unused var warning

            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu,DUMMY_VAR__);


            current_statement_begin__ = 14;
            lp_accum__.add(cauchy_log<propto__>(sigma_society, 0, 1));
            current_statement_begin__ = 15;
            lp_accum__.add(normal_log<propto__>(a_society, 0, sigma_society));
            current_statement_begin__ = 16;
            lp_accum__.add(normal_log<propto__>(bp, 0, 1));
            current_statement_begin__ = 17;
            lp_accum__.add(normal_log<propto__>(a, 0, 10));
            current_statement_begin__ = 18;
            for (int i = 1; i <= 10; ++i) {

                current_statement_begin__ = 19;
                stan::model::assign(mu, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            ((a + get_base1(a_society,get_base1(society,i,"society",1),"a_society",1)) + (bp * get_base1(logpop,i,"logpop",1))), 
                            "assigning variable mu");
                current_statement_begin__ = 20;
                stan::model::assign(mu, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            stan::model::deep_copy(stan::math::exp(get_base1(mu,i,"mu",1))), 
                            "assigning variable mu");
            }
            current_statement_begin__ = 22;
            lp_accum__.add(poisson_log<propto__>(total_tools, mu));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("a");
        names__.push_back("bp");
        names__.push_back("a_society");
        names__.push_back("sigma_society");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(10);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "m12_6_1_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double a = in__.scalar_constrain();
        double bp = in__.scalar_constrain();
        vector_d a_society = in__.vector_constrain(10);
        double sigma_society = in__.scalar_lb_constrain(0);
        vars__.push_back(a);
        vars__.push_back(bp);
            for (int k_0__ = 0; k_0__ < 10; ++k_0__) {
            vars__.push_back(a_society[k_0__]);
            }
        vars__.push_back(sigma_society);

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {



            // validate transformed parameters

            // write transformed parameters
            if (include_tparams__) {
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "m12_6_1_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "bp";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= 10; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "a_society" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_society";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "bp";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= 10; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "a_society" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_society";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef m12_6_1_model_namespace::m12_6_1_model stan_model;

